name: Build API Docker CI

on:
  push:
    branches:
      - main
    paths:
      - PublicLibrarySystem-API/**
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        # - name: Create and use unique Docker context
        #   run: |
        #     docker context create context-${{ github.run_id }}-${{ github.job }} || true
        #     docker context use context-${{ github.run_id }}-${{ github.job }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            #endpoint: context-${{ github.run_id }}-${{ github.job }}
            driver: docker-container

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./PublicLibrarySystem-API
            file: ./PublicLibrarySystem-API/PublicLibrarySystem-API/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/public-library-system:api
        
        - name: Trigger Deploy Workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: build-completed